### PR TITLE
Openscad option to split the spacer layer of the case into fourths.

### PR DESCRIPTION
**Pull request by cy384**
I've added a little code that allows for splitting the spacer layer of the case into fourths, giving more flexbility in fitting the pieces onto a sheet for laser cutting (specifically, I wanted to fit it all onto one P2 sheet of 3mm acrylic from Ponoko).  Kudos for inspiration goes to [this geekhack thread by Constantine](https://geekhack.org/index.php?topic=57007.0).

I'm still waiting on my Ponoko order to arrive in the mail, so you may want to wait until I've tested that it all fits nicely before merging.

### CODE REVIEW

**Comment by technomancy** [comment]
Thanks!

I realized this is a bit unclear from the docs, but the GeekHack thread
you linked to states that there are some differences between the
openscad design and the canonical design; in particular it bulges at the
bottom a bit differently and has the inner screws closer together. It
would hardly be noticeable unless you place the two side-by-side, but I
thought I should mention it.

**Comment by cy384** [comment]
Ah, yes, I wasn't exactly sure which case design was the most official; I just went with the openscad one because I like openscad.  Also, I'll be hand wiring, so I wasn't too worried about exact compatibility.

**Comment by cy384** [comment]
My order just arrived, and I can confirm that the quartered design works.  It loses a little rigidity in the spacer layers, but once assembled I don't think there's any noticeable weakness.

**Comment by ckhroulev** [comment]
Excellent!

(I wrote the OpenSCAD version hoping that it will make it easier to tweak the case design (I did not need it myself), so it's great to hear that it works!)

**Comment by technomancy** [comment]
Great; glad you got that working.

**Pull request merged**
